management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    hikari:
      validationTimeout: 100000
      maximumPoolSize: 10
com.sap:
  cds:
    modelName: csn.json